export const MaestroPoolManagerABI = [
  {
    type: "function",
    name: "requestMembership",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "membershipCallback",
    inputs: [
      { name: "response", type: "bytes" },
      { name: "extraData", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "hasJoined",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pool",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "JOIN_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_SCORE",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UNITS_PER_AGENT",
    inputs: [],
    outputs: [{ name: "", type: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FEE_COLLECTOR",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AgentJoined",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "agentWallet", type: "address", indexed: true },
      { name: "score", type: "uint256", indexed: false },
    ],
  },
  {
    type: "error",
    name: "OffchainLookup",
    inputs: [
      { name: "sender", type: "address" },
      { name: "urls", type: "string[]" },
      { name: "callData", type: "bytes" },
      { name: "callbackFunction", type: "bytes4" },
      { name: "extraData", type: "bytes" },
    ],
  },
  { type: "error", name: "NotAgentOwner", inputs: [] },
  { type: "error", name: "AlreadyJoined", inputs: [] },
  { type: "error", name: "AgentNotRegistered", inputs: [] },
  {
    type: "error",
    name: "ScoreBelowMinimum",
    inputs: [
      { name: "score", type: "uint256" },
      { name: "minScore", type: "uint256" },
    ],
  },
  { type: "error", name: "InsufficientFee", inputs: [] },
  { type: "error", name: "FeeTransferFailed", inputs: [] },
  { type: "error", name: "BAD_SIG", inputs: [] },
  { type: "error", name: "SCORE_TOO_OLD", inputs: [] },
] as const;
